{% set name = "ai-traineree" %}
{% set version = "0.9.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ai_traineree-{{ version }}.tar.gz
  sha256: d9c1fabbf39833450b21705e0146f53c2388d253e5f4a1910df41691b241b08f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv >=0.4.9
    - hatchling
    - pip
    - pytorch
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - pytorch
    - jsons >=1.4.0
    - gymnasium ==1.0.0
    - matplotlib-base >=3.7.5

test:
  imports:
    - aitraineree
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/laszukdawid/ai-traineree
  summary: Yet another zoo of (Deep) Reinforcement Learning methods in Python using PyTorch
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - laszukdawid
